version: v1
server:
  port: 8083
  servlet:
    context-path: /@project.artifactId@
datasource:
  pgs:
    jdbcUrl: jdbc:postgresql://${PGS_HOST_P}:5432/postgres
    password: 123456
    username: postgres